include: package:very_good_analysis/analysis_options.3.1.0.yaml

linter:
  rules:
    sort_constructors_first: false
    public_member_api_docs: false
    constant_identifier_names: false
    avoid_positional_boolean_parameters: false
    require_trailing_commas: true
